version: 37
jobs:
- name: GitHub Push
  steps:
  - !PushRepository
    name: Github push sync
    remoteUrl: https://github.com/VnUgE/Plugins.Essentials.git
    userName: VnUgE
    passwordSecret: github-access-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PushRepository
    name: Codeberg push sync
    remoteUrl: https://codeberg.org/VnUgE/Plugins.Essentials.git
    userName: VnUgE
    passwordSecret: codeberg-access-token
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger
    projects: Plugins.Essentials
  - !BranchUpdateTrigger
    projects: Plugins.Essentials
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600

- name: Unit Testing
  jobExecutor: windows
  steps:
  - !CommandStep
    name: Clone local deps
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_name@ --branch @branch@
        git clone @server_url@/VNLib.Core core --branch master
        git clone @server_url@/VNLib.Data.Caching --branch master
        git clone @server_url@/VNLib.Plugins.Extensions --branch master
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: dev-init core
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        cd core
        task -t Module.Taskfile.yaml dev-init
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: run unit tests
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        vnbuild test --include @project_name@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: '** -master'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Staging build
  jobExecutor: windows
  steps:
  - !CommandStep
    name: Clone local deps
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_name@ --branch @branch@
        git clone @server_url@/VNLib.Core core --branch master
        git clone @server_url@/VNLib.Data.Caching --branch master
        git clone @server_url@/VNLib.Plugins.Extensions --branch master
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        dotnet gitversion core /updateprojectfiles
        dotnet gitversion VNLib.Data.Caching /updateprojectfiles
        dotnet gitversion VNLib.Plugins.Extensions /updateprojectfiles
        vnbuild build --no-delay --include @project_name@ --verbose
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: mock publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish -i @project_name@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: develop
  jobDependencies:
  - jobName: Unit Testing
    requireSuccessful: true
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400

- name: Publish master
  jobExecutor: publish-agents
  steps:
  - !CommandStep
    name: Clone local deps
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        git clone @server_url@/@project_name@ --branch @branch@
        git clone @server_url@/VNLib.Core core --branch master
        git clone @server_url@/VNLib.Data.Caching --branch master
        git clone @server_url@/VNLib.Plugins.Extensions --branch master
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Create git tag
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        cd @project_name@
        task -t Module.Taskfile.yaml tag-current-commit
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        dotnet gitversion core /updateprojectfiles
        dotnet gitversion VNLib.Data.Caching /updateprojectfiles
        dotnet gitversion VNLib.Plugins.Extensions /updateprojectfiles
        vnbuild build --no-delay --include @project_name@
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: VNBuild publish
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands: |
        vnbuild publish -i @project_name@ --ftp "@secret:ftp_server_address@" --sign
    envVars:
    - name: FTP_USERNAME
      value: '@secret:ftp_username@'
    - name: FTP_PASSWORD
      value: '@secret:ftp_password@'
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
